name: Daily code format check

on:
  schedule:
    - cron: 0 0 * * * # Every day at midnight (UTC)
  workflow_dispatch:
  
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run dotnet format
        id: format
        uses: jfversluis/dotnet-format@1.0.7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "fix"
          #only-changed-files: true # only works for PRs
          workspace: "src/BUTR.CrashReportViewer.sln"
    
      - name: Commit files
        if: steps.format.outputs.has-changes == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -a -m 'Automated dotnet-format update'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automated PR to fix formatting errors'
          body: |
            Automated PR to fix formatting errors
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          labels: code-formatting
          assignees: aragas, artifixer, zijistark
          reviewers: aragas, artifixer, zijistark
          branch: code-formatting/fix-codeformatting

      # Pushing won't work to forked repos
      # - name: Commit files
      #   if: steps.format.outputs.has-changes == 'true'
      #   run: |
      #     git config --local user.name "github-actions[bot]"
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git commit -a -m 'Automated dotnet-format update
      #     Co-authored-by: ${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.id }}+${{ github.event.pull_request.user.login }}@users.noreply.github.com>'

      # - name: Push changes
      #   if: steps.format.outputs.has-changes == 'true'
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.event.pull_request.head.ref }}
